<a href="https://colab.research.google.com/github/yaajnu/ColabNotebooks/blob/master/Chapter_4(Practice).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_wine
import pandas as pd
wine=load_wine()
wine.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [ ]:
X=wine['data']

In [ ]:
print(wine["DESCR"])

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [ ]:
Y=wine['target']

In [ ]:
df=pd.DataFrame(wine['data'],columns=wine['feature_names'])
df['class']=wine['target']
df

alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  class
0      14.23        1.71  2.43  ...                          3.92   1065.0      0
1      13.20        1.78  2.14  ...                          3.40   1050.0      0
2      13.16        2.36  2.67  ...                          3.17   1185.0      0
3      14.37        1.95  2.50  ...                          3.45   1480.0      0
4      13.24        2.59  2.87  ...                          2.93    735.0      0
..       ...         ...   ...  ...                           ...      ...    ...
173    13.71        5.65  2.45  ...                          1.74    740.0      2
174    13.40        3.91  2.48  ...                          1.56    750.0      2
175    13.27        4.28  2.26  ...                          1.56    835.0      2
176    13.17        2.59  2.37  ...                          1.62    840.0      2
177    14.13        4.10  2.74  ...                          1.60    560.0      2

[178 rows x 14 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,random_state=42)

In [ ]:
some_wine=X[150,:]

In [ ]:
x_train.shape

(133, 13)

In [ ]:
x_test.shape

(45, 13)

In [ ]:
from sklearn.linear_model import LogisticRegression
lin_reg=LogisticRegression(penalty='l2',multi_class='multinomial',random_state=42)
lin_reg.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
lin_reg.predict(some_wine.reshape(1,-1))

array([2])

In [ ]:
lin_reg.predict_proba(some_wine.reshape(1,-1))

array([[1.18443792e-04, 2.33650044e-04, 9.99647906e-01]])

In [ ]:
lin_reg.decision_function(some_wine.reshape(1,-1))

array([[-3.24003527, -2.56064933,  5.80068461]])

In [ ]:
from sklearn.model_selection import cross_val_score,cross_val_predict
cross_val_score(lin_reg,x_train,y_train,scoring='accuracy',cv=3)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([0.88888889, 0.95454545, 0.93181818])

In [ ]:
from sklearn.metrics import confusion_matrix
a=cross_val_predict(lin_reg,x_test,y_test,cv=3)
confusion_matrix(y_test,a)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([[13,  2,  0],
       [ 0, 18,  0],
       [ 0,  0, 12]])

In [ ]:
w=(y_test==0)
w.sum()


15

In [ ]:
a

array([1, 0, 2, 0, 1, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0, 2, 2, 1, 2, 0, 1, 1, 1,
       2])

In [ ]:
from sklearn.metrics import precision_score,recall_score
precision_score(y_test,a,average='weighted')

0.9600000000000001

In [ ]:
recall_score(y_test,a,average='weighted')

0.9555555555555556

**QUESTION 12 CHAPTER 4**

In [ ]:
x_train 

array([[1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       [1.208e+01, 2.080e+00, 1.700e+00, ..., 1.270e+00, 2.960e+00,
        7.100e+02],
       [1.242e+01, 4.430e+00, 2.730e+00, ..., 9.200e-01, 3.120e+00,
        3.650e+02],
       ...,
       [1.438e+01, 1.870e+00, 2.380e+00, ..., 1.200e+00, 3.000e+00,
        1.547e+03],
       [1.269e+01, 1.530e+00, 2.260e+00, ..., 9.600e-01, 2.060e+00,
        4.950e+02],
       [1.234e+01, 2.450e+00, 2.460e+00, ..., 8.000e-01, 3.380e+00,
        4.380e+02]])

In [ ]:
import numpy as np

In [ ]:
def softmax(logits):
  exps=np.exp(logits)
  exps_sum=np.sum(exps,keepdims=True)
  return exps/exps_sum

In [ ]:
n_inputs=x_train.shape[1]

In [ ]:
n_outputs=len(np.unique(y_train))

In [ ]:
alpha=0.01
m=len(x_train)
Theta=np.random.randn(n_inputs,n_outputs)
for epoch in range(5001):
  logits=x_train.dot(Theta)
  prob=softmax(logits)
  cost=-np.mean(np.sum(np.dot(y_train.T,np.log(prob+0.000000001))))
  error=prob-y_train.reshape(133,1)
  if epoch%500==0:
    print(epoch,cost)
  gradients=1/m *np.sum(np.dot(error.T,x_train))
  Theta=Theta - alpha*gradients


0 7771.224688854907
500 nan
1000 nan
1500 nan
2000 nan
2500 nan


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


3000 nan
3500 nan
4000 nan
4500 nan
5000 nan
